spring:
  thymeleaf:
    mode: HTML
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: ***
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
logging:
  level:
    root: info
    com.blog: debug
  file:
    path: log/blog.log
server:
  port: 8081
comment.avatar: /images/visitor.jpg
